const interObj = [
  {
    number: 1,
    names: [
      "toldo",
      "julio cesar",
      "peruzzi",
      "frey",
      "pagliuca",
      "abate",
      "malgioglio",
      "zenga",
      "bordon",
      "recchi",
      "vieri",
      "sarti",
      "buffon",
      "bugatti",
      "matteucci",
      "ghezzi",
      "puccioni",
    ],
  },
  {
    number: 2,
    names: [
      "hakimi",
      "godin",
      "vrsaljko",
      "lopez",
      "andreolli",
      "jonathan",
      "cordoba",
      "panucci",
      "paganin",
      "baresi",
      "ferri",
      "bergomi",
      "canuti",
      "gasparini",
      "guida",
      "oriali",
      "bini",
      "guida",
      "catellani",
      "fedele",
      "bini",
      "oriali",
      "giubertoni",
      "bellugi",
      "burgnich",
      "picchi",
      "facchetti",
      "masiero",
      "caloi",
      "guarneri",
      "fongaro",
      "blason",
      "giacomazzi",
    ],
  },
  {
    number: 3,
    names: [
      "burdisso",
      "kallon",
      "macellari",
      "colonnese",
      "tarantino",
      "pistone",
      "seno",
      "centofanti",
      "festa",
      "conte",
      "fontolan",
      "orlando",
      "shalimov",
      "paganin",
      "tramezzani",
      "de agostini",
      "brehme",
      "calcaterra",
      "marangon",
      "mandorlini",
      "baresi",
      "bergomi",
      "marini",
      "fedele",
      "canuti",
      "bini",
      "giubertoni",
      "scala",
      "fedele",
      "guida",
      "catellani",
      "oriali",
      "masiero",
      "fongaro",
      "valade",
      "vincenzi",
      "giacomazzi",
      "giovannini",
      "padulazzi",
    ],
  },
  {
    number: 4,
    names: [
      "zanetti",
      "fresi",
      "seno",
      "orlando",
      "jonk",
      "manicone",
      "shalimov",
      "paganin",
      "bianchi",
      "paganin",
      "berti",
      "ferri",
      "battistini",
      "stringa",
      "berti",
      "verdelli",
      "matteoli",
      "brehme",
      "baresi",
      "bagni",
      "pasinato",
      "ferri",
      "oriali",
      "pasinato",
      "pasinato",
      "fedele",
      "marini",
      "galbiati",
      "scala",
      "catellani",
      "bertini",
      "fedele",
      "bellugi",
      "bedin",
      "tagnin",
      "bolchi",
      "zaglio",
      "balleri",
      "invernizzi",
      "masiero",
      "vincenzi",
      "fattori",
      "neri",
    ],
  },
  {
    number: 5,
    names: [
      "gagliardini",
      "felipe melo",
      "juan jesus",
      "stankovic",
      "emre",
      "padalino",
      "blanc",
      "cauet",
      "galante",
      "fresi",
      "festa",
      "dell'anno",
      "baggio",
      "paganin",
      "bergomi",
      "ferri",
      "mandorlini",
      "marini",
      "collovati",
      // "bachlechner",
      // "mozzini",
      // "canuti",
      // "guida",
      // "gasparini",
      // "facchetti",
      // "catellani",
      // "bini",
      // "bellugi",
      // "giubertoni",
      // "landini",
      // "guarneri",
      // "bicchierai",
      // "cardarelli",
    ],
  },
  {
    number: 6,
    names: [
      "de vrij",
      "joao mario",
      "dodo",
      "andreolli",
      "silvestre",
      "lucio",
      "maxwell",
      "zanetti",
      "serena",
      "sousa",
      "djorkaeff",
      "roberto carlos",
      "bia",
      "bergomi",
      "battistini",
      "montanari",
      "paganin",
      "battistini",
      "verdelli",
      "ciocci",
      "mandorlini",
      "passarella",
      "cucchi",
      "mandorlini",
      "ferri",
      "baresi",
      // "bachlechner",
      // "bini",
      // "anastasi",
      // "galbiati",
      // "giubertoni",
      // "bini",
      // "facchetti",
      // "burgnich",
      // "cella",
      // "picchi",
      // "balleri",
      // "dellagiovanna",
      // "venturi",
      // "vincenzi",
      // "nesti",
      // "invernizzi",
      // "neri",
      // "padulazzi",
      // "miglioli",
    ],
  },
  {
    number: 7,
    names: [
      "sanchez",
      "karamoh",
      "cancelo",
      "kondogbia",
      "osvaldo",
      "belfodil",
      "schelotto",
      "coutinho",
      "pazzini",
      "quaresma",
      "figo",
      "van der meyde",
      "conceicao",
      "pacheco",
      "keane",
      "moriero",
      "fresi",
      "zanetti",
      "orlandini",
      "berti",
      "paganin",
      "dell'anno",
      "orlando",
      "bianchi",
      "desideri",
      "stringara",
      "morello",
      "cucchi",
      "bianchi",
      "matteoli",
      "fanna",
      "cucchi",
      "causio",
      "sabato",
      "coeck",
      "marini",
      "bagni",
      "oriali",
      "caso",
      // "marini",
      // "anastasi",
      // "galbiati",
      // "pavone",
      // "rossi",
      // "muraro",
      // "mariani",
      // "massa",
      // "magistrelli",
      // "moro",
    ],
  },
  {
    number: 8,
    names: [
      "gosens",
      "vecino",
      "rafinha",
      "jovetic",
      "palacio",
      "thiago motta",
      "ibrahimovic",
      "pizarro",
      "davids",
      "lamouchi",
      "farinos",
      "jugovic",
      "winter",
      "ince",
      "berti",
      "seno",
      "shalimov",
      "jonk",
      "dell'anno",
      "manicone",
      "berti",
      "battistini",
      "pizzi",
      "matteoli",
      "scifo",
      "tardelli",
      "sabato",
    ],
  },
  {
    number: 9,
    names: [
      "dzeko",
      "lukaku",
      "icardi",
      "eto'o",
      "forlan",
      "cruz",
      "crespo",
      "ronaldo",
      "zamorano",
      "centofanti",
      "ganz",
      "delvecchio",
      "pancev",
      "berti",
      "shalimov",
      "dell'anno",
      "schillaci",
      "fontolan",
      "sosa",
      "ciocci",
      "klinsmann",
      "diaz",
      "fanna",
      "altobelli",
      "mazzola",
      "boninsegna",
    ],
  },
  {
    number: 10,
    names: [
      "lautaro martinez",
      "joao mario",
      "jovetic",
      "kovacic",
      "sneijder",
      "adriano",
      "dalmat",
      "morfeo",
      "seedorf",
      "baggio",
      "ronaldo",
      "carbone",
      "berti",
      "bergkamp",
      "shalimov",
      "stringara",
      "cucchi",
      "matthaus",
      "mandorlini",
      "scifo",
      "matteoli",
      "sosa",
      "ciocci",
      "klinsmann",
      "diaz",
      "fanna",
      "altobelli",
      "mazzola",
      "boninsegna",
    ],
  },
];
